name: elpigo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  get_cli: ^1.8.1
  google_fonts: ^6.2.1
  firebase_core: ^2.31.1
  image_picker: ^1.1.1
  cloud_firestore: ^4.17.4
  firebase_storage: ^11.7.6
  firebase_auth: ^4.19.6

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets: 
    - assets/logo.png
  uses-material-design: true

